"""Add password_hash field to users table

Revision ID: dfd808057445
Revises: 09bab206b2ce
Create Date: 2025-12-09 13:14:34.044629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dfd808057445'
down_revision: Union[str, None] = '09bab206b2ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('projects', 'hourly_rate',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Integer(),
               nullable=True,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('projects', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_projects_owner_id', table_name='projects')
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.drop_constraint('fk_projects_owner', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['owner_id'], ['id'])
    op.drop_column('projects', 'updated_at')
    op.drop_column('projects', 'color')
    op.alter_column('tasks', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=mysql.ENUM('todo', 'in_progress', 'done', collation='utf8mb4_unicode_ci'),
               nullable=True,
               existing_server_default=sa.text("'todo'"))
    op.alter_column('tasks', 'total_time',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('tasks', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_tasks_project_id', table_name='tasks')
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.drop_constraint('fk_tasks_project', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'])
    op.drop_column('tasks', 'updated_at')
    op.alter_column('time_entries', 'note',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index('idx_time_entries_task_user_time', table_name='time_entries')
    op.create_index(op.f('ix_time_entries_id'), 'time_entries', ['id'], unique=False)
    op.drop_constraint('fk_time_entries_user', 'time_entries', type_='foreignkey')
    op.drop_constraint('fk_time_entries_task', 'time_entries', type_='foreignkey')
    op.create_foreign_key(None, 'time_entries', 'tasks', ['task_id'], ['id'])
    op.create_foreign_key(None, 'time_entries', 'users', ['user_id'], ['id'])
    op.drop_column('time_entries', 'created_at')
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=True,
               existing_server_default=sa.text("'user'"))
    op.alter_column('users', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('username', table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('users', sa.Column('hashed_password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index('username', 'users', ['username'], unique=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=False,
               existing_server_default=sa.text("'user'"))
    op.drop_column('users', 'password_hash')
    op.add_column('time_entries', sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.drop_constraint(None, 'time_entries', type_='foreignkey')
    op.drop_constraint(None, 'time_entries', type_='foreignkey')
    op.create_foreign_key('fk_time_entries_task', 'time_entries', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_time_entries_user', 'time_entries', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_time_entries_id'), table_name='time_entries')
    op.create_index('idx_time_entries_task_user_time', 'time_entries', ['task_id', 'user_id', 'start_time'], unique=False)
    op.alter_column('time_entries', 'note',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
    op.add_column('tasks', sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('fk_tasks_project', 'tasks', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.create_index('idx_tasks_project_id', 'tasks', ['project_id'], unique=False)
    op.alter_column('tasks', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tasks', 'total_time',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('tasks', 'status',
               existing_type=mysql.ENUM('todo', 'in_progress', 'done', collation='utf8mb4_unicode_ci'),
               nullable=False,
               existing_server_default=sa.text("'todo'"))
    op.alter_column('tasks', 'description',
               existing_type=sa.String(length=1000),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
    op.add_column('projects', sa.Column('color', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True))
    op.add_column('projects', sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('fk_projects_owner', 'projects', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.create_index('idx_projects_owner_id', 'projects', ['owner_id'], unique=False)
    op.alter_column('projects', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('projects', 'hourly_rate',
               existing_type=sa.Integer(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('projects', 'description',
               existing_type=sa.String(length=500),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
    # ### end Alembic commands ###
